version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.0-ce
    working_directory: /api
    branches:
      only:
        - master
        - devlop
    steps:
      - setup_remote_docker
      - run:
          name: Show Info
          command: |
            docker version
            docker info
      - checkout
      - run:
          name: Build the current image
          command: |
            TAG=build
            docker build -f Dockerfile -t ritsse/node-api:$TAG .
      - run:
          name: Distribute
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                TAG=2.0.$CIRCLE_BUILD_NUM
                docker tag ritsse/node-api:build ritsse/node-api:latest
                docker tag ritsse/node-api:build ritsse/node-api:$TAG
                docker push ritsse/node-api:$TAG
                docker push ritsse/node-api:latest
            else
                TAG=dev-2.0.$CIRCLE_BUILD_NUM
                docker tag ritsse/node-api:build ritsse/node-api:dev-latest
                docker tag ritsse/node-api:build ritsse/node-api:$TAG
                docker push ritsse/node-api:$TAG
                docker push ritsse/node-api:dev-latest
            fi;
